// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/heisenbergoss/go-turtles/internal/data"
)

func newFact(db *gorm.DB, opts ...gen.DOOption) fact {
	_fact := fact{}

	_fact.factDo.UseDB(db, opts...)
	_fact.factDo.UseModel(&data.Fact{})

	tableName := _fact.factDo.TableName()
	_fact.ALL = field.NewAsterisk(tableName)
	_fact.ID = field.NewUint(tableName, "id")
	_fact.CreatedAt = field.NewTime(tableName, "created_at")
	_fact.UpdatedAt = field.NewTime(tableName, "updated_at")
	_fact.DeletedAt = field.NewField(tableName, "deleted_at")
	_fact.ParentID = field.NewUint(tableName, "parent_id")
	_fact.Title = field.NewString(tableName, "title")
	_fact.Content = field.NewString(tableName, "content")
	_fact.SourceURL = field.NewString(tableName, "source_url")
	_fact.Children = factHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "data.Fact"),
		Parent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Parent", "data.Fact"),
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Children", "data.Fact"),
		},
	}

	_fact.Parent = factBelongsToParent{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parent", "data.Fact"),
	}

	_fact.fillFieldMap()

	return _fact
}

type fact struct {
	factDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	ParentID  field.Uint
	Title     field.String
	Content   field.String
	SourceURL field.String
	Children  factHasManyChildren

	Parent factBelongsToParent

	fieldMap map[string]field.Expr
}

func (f fact) Table(newTableName string) *fact {
	f.factDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fact) As(alias string) *fact {
	f.factDo.DO = *(f.factDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fact) updateTableName(table string) *fact {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewUint(table, "id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.DeletedAt = field.NewField(table, "deleted_at")
	f.ParentID = field.NewUint(table, "parent_id")
	f.Title = field.NewString(table, "title")
	f.Content = field.NewString(table, "content")
	f.SourceURL = field.NewString(table, "source_url")

	f.fillFieldMap()

	return f
}

func (f *fact) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fact) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 10)
	f.fieldMap["id"] = f.ID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
	f.fieldMap["parent_id"] = f.ParentID
	f.fieldMap["title"] = f.Title
	f.fieldMap["content"] = f.Content
	f.fieldMap["source_url"] = f.SourceURL

}

func (f fact) clone(db *gorm.DB) fact {
	f.factDo.ReplaceConnPool(db.Statement.ConnPool)
	f.Children.db = db.Session(&gorm.Session{Initialized: true})
	f.Children.db.Statement.ConnPool = db.Statement.ConnPool
	f.Parent.db = db.Session(&gorm.Session{Initialized: true})
	f.Parent.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f fact) replaceDB(db *gorm.DB) fact {
	f.factDo.ReplaceDB(db)
	f.Children.db = db.Session(&gorm.Session{})
	f.Parent.db = db.Session(&gorm.Session{})
	return f
}

type factHasManyChildren struct {
	db *gorm.DB

	field.RelationField

	Parent struct {
		field.RelationField
	}
	Children struct {
		field.RelationField
	}
}

func (a factHasManyChildren) Where(conds ...field.Expr) *factHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a factHasManyChildren) WithContext(ctx context.Context) *factHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a factHasManyChildren) Session(session *gorm.Session) *factHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a factHasManyChildren) Model(m *data.Fact) *factHasManyChildrenTx {
	return &factHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

func (a factHasManyChildren) Unscoped() *factHasManyChildren {
	a.db = a.db.Unscoped()
	return &a
}

type factHasManyChildrenTx struct{ tx *gorm.Association }

func (a factHasManyChildrenTx) Find() (result []*data.Fact, err error) {
	return result, a.tx.Find(&result)
}

func (a factHasManyChildrenTx) Append(values ...*data.Fact) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a factHasManyChildrenTx) Replace(values ...*data.Fact) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a factHasManyChildrenTx) Delete(values ...*data.Fact) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a factHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a factHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

func (a factHasManyChildrenTx) Unscoped() *factHasManyChildrenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type factBelongsToParent struct {
	db *gorm.DB

	field.RelationField
}

func (a factBelongsToParent) Where(conds ...field.Expr) *factBelongsToParent {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a factBelongsToParent) WithContext(ctx context.Context) *factBelongsToParent {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a factBelongsToParent) Session(session *gorm.Session) *factBelongsToParent {
	a.db = a.db.Session(session)
	return &a
}

func (a factBelongsToParent) Model(m *data.Fact) *factBelongsToParentTx {
	return &factBelongsToParentTx{a.db.Model(m).Association(a.Name())}
}

func (a factBelongsToParent) Unscoped() *factBelongsToParent {
	a.db = a.db.Unscoped()
	return &a
}

type factBelongsToParentTx struct{ tx *gorm.Association }

func (a factBelongsToParentTx) Find() (result *data.Fact, err error) {
	return result, a.tx.Find(&result)
}

func (a factBelongsToParentTx) Append(values ...*data.Fact) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a factBelongsToParentTx) Replace(values ...*data.Fact) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a factBelongsToParentTx) Delete(values ...*data.Fact) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a factBelongsToParentTx) Clear() error {
	return a.tx.Clear()
}

func (a factBelongsToParentTx) Count() int64 {
	return a.tx.Count()
}

func (a factBelongsToParentTx) Unscoped() *factBelongsToParentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type factDo struct{ gen.DO }

type IFactDo interface {
	gen.SubQuery
	Debug() IFactDo
	WithContext(ctx context.Context) IFactDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFactDo
	WriteDB() IFactDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFactDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFactDo
	Not(conds ...gen.Condition) IFactDo
	Or(conds ...gen.Condition) IFactDo
	Select(conds ...field.Expr) IFactDo
	Where(conds ...gen.Condition) IFactDo
	Order(conds ...field.Expr) IFactDo
	Distinct(cols ...field.Expr) IFactDo
	Omit(cols ...field.Expr) IFactDo
	Join(table schema.Tabler, on ...field.Expr) IFactDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFactDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFactDo
	Group(cols ...field.Expr) IFactDo
	Having(conds ...gen.Condition) IFactDo
	Limit(limit int) IFactDo
	Offset(offset int) IFactDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFactDo
	Unscoped() IFactDo
	Create(values ...*data.Fact) error
	CreateInBatches(values []*data.Fact, batchSize int) error
	Save(values ...*data.Fact) error
	First() (*data.Fact, error)
	Take() (*data.Fact, error)
	Last() (*data.Fact, error)
	Find() ([]*data.Fact, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*data.Fact, err error)
	FindInBatches(result *[]*data.Fact, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*data.Fact) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFactDo
	Assign(attrs ...field.AssignExpr) IFactDo
	Joins(fields ...field.RelationField) IFactDo
	Preload(fields ...field.RelationField) IFactDo
	FirstOrInit() (*data.Fact, error)
	FirstOrCreate() (*data.Fact, error)
	FindByPage(offset int, limit int) (result []*data.Fact, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFactDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f factDo) Debug() IFactDo {
	return f.withDO(f.DO.Debug())
}

func (f factDo) WithContext(ctx context.Context) IFactDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f factDo) ReadDB() IFactDo {
	return f.Clauses(dbresolver.Read)
}

func (f factDo) WriteDB() IFactDo {
	return f.Clauses(dbresolver.Write)
}

func (f factDo) Session(config *gorm.Session) IFactDo {
	return f.withDO(f.DO.Session(config))
}

func (f factDo) Clauses(conds ...clause.Expression) IFactDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f factDo) Returning(value interface{}, columns ...string) IFactDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f factDo) Not(conds ...gen.Condition) IFactDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f factDo) Or(conds ...gen.Condition) IFactDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f factDo) Select(conds ...field.Expr) IFactDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f factDo) Where(conds ...gen.Condition) IFactDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f factDo) Order(conds ...field.Expr) IFactDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f factDo) Distinct(cols ...field.Expr) IFactDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f factDo) Omit(cols ...field.Expr) IFactDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f factDo) Join(table schema.Tabler, on ...field.Expr) IFactDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f factDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFactDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f factDo) RightJoin(table schema.Tabler, on ...field.Expr) IFactDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f factDo) Group(cols ...field.Expr) IFactDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f factDo) Having(conds ...gen.Condition) IFactDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f factDo) Limit(limit int) IFactDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f factDo) Offset(offset int) IFactDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f factDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFactDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f factDo) Unscoped() IFactDo {
	return f.withDO(f.DO.Unscoped())
}

func (f factDo) Create(values ...*data.Fact) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f factDo) CreateInBatches(values []*data.Fact, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f factDo) Save(values ...*data.Fact) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f factDo) First() (*data.Fact, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*data.Fact), nil
	}
}

func (f factDo) Take() (*data.Fact, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*data.Fact), nil
	}
}

func (f factDo) Last() (*data.Fact, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*data.Fact), nil
	}
}

func (f factDo) Find() ([]*data.Fact, error) {
	result, err := f.DO.Find()
	return result.([]*data.Fact), err
}

func (f factDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*data.Fact, err error) {
	buf := make([]*data.Fact, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f factDo) FindInBatches(result *[]*data.Fact, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f factDo) Attrs(attrs ...field.AssignExpr) IFactDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f factDo) Assign(attrs ...field.AssignExpr) IFactDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f factDo) Joins(fields ...field.RelationField) IFactDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f factDo) Preload(fields ...field.RelationField) IFactDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f factDo) FirstOrInit() (*data.Fact, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*data.Fact), nil
	}
}

func (f factDo) FirstOrCreate() (*data.Fact, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*data.Fact), nil
	}
}

func (f factDo) FindByPage(offset int, limit int) (result []*data.Fact, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f factDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f factDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f factDo) Delete(models ...*data.Fact) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *factDo) withDO(do gen.Dao) *factDo {
	f.DO = *do.(*gen.DO)
	return f
}
