// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateFactInput struct {
	Title     string  `json:"title"`
	Content   string  `json:"content"`
	SourceURL *string `json:"sourceURL,omitempty"`
	ParentID  *string `json:"parentID,omitempty"`
}

type Fact struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Content   string  `json:"content"`
	SourceURL *string `json:"sourceURL,omitempty"`
	Parent    *Fact   `json:"parent,omitempty"`
	Children  []*Fact `json:"children"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateFactInput struct {
	Title     *string `json:"title,omitempty"`
	Content   *string `json:"content,omitempty"`
	SourceURL *string `json:"sourceURL,omitempty"`
	ParentID  *string `json:"parentID,omitempty"`
}
