// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Fact struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Content   string  `json:"content"`
	SourceURL *string `json:"sourceURL,omitempty"`
	Parent    *Fact   `json:"parent,omitempty"`
	Children  []*Fact `json:"children"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Query struct {
}
