name: Continuous Integration

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-backend:
    name: Test Go Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run Go Tests
        run: go test -v -race ./...
        working-directory: ./api

  test-frontend-e2e:
    name: Frontend E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./webapp

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # This step now runs migrate, then seed, then the server.
      - name: Setup and Run Backend
        env:
          DSN: "host=localhost user=testuser password=testpassword dbname=testdb port=5432 sslmode=disable"
        run: |
          # Wait a moment for the DB service to be fully available
          sleep 5
          # 1. Run the migration to create tables
          echo "Running Database Migration..."
          go run ./cmd/migrate/main.go
          # 2. Run the seeder to populate the tables
          echo "Seeding temporary database..."
          go run ./cmd/seeder/main.go
          # 3. Run the API server in the background
          echo "Starting API server..."
          go run ./cmd/server/server.go &
          # Wait for the API server to start up
          sleep 5
        working-directory: ./api

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node.js with pnpm Caching
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: webapp/pnpm-lock.yaml

      - name: Install Frontend Dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Run Playwright E2E Tests
        env:
          VITE_API_URL: http://localhost:8080/query
        run: pnpm test:e2e
