# .github/workflows/deploy-api.yml

name: Deploy Go API to Cloud Run

# This workflow runs on any push to the 'main' branch.
# 'workflow_dispatch' allows you to run it manually from the GitHub Actions tab.
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Define environment variables used throughout the workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1 # The location of your Artifact Registry
  SERVICE_NAME: turtles-api # The name of your Cloud Run service
  REGION: us-central1 # The region of your Cloud Run service

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Add the repository name to the environment variables
    env:
      GAR_REPOSITORY: turtles-repo
      IMAGE_NAME: turtles-api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # This step builds the Docker image and pushes it to Google Artifact Registry
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          platforms: linux/amd64
          # CORRECTED a 'tags' line to use the GAR_REPOSITORY variable
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      # This final step deploys the newly pushed image to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          # CORRECTED the 'image' path to match the one we pushed
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          env_vars: |
            DSN=${{ secrets.PROD_DB_DSN }}
